// <auto-generated />
using System;
using Colony.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Colony.Data.Migrations
{
    [DbContext(typeof(ColonyContext))]
    [Migration("20190617235754_CreateAntTypeTable")]
    partial class CreateAntTypeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Colony.Ants.Types.AntType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("AntType");
                });
#pragma warning restore 612, 618
        }
    }
}
